<a href="https://colab.research.google.com/github/24mca00py0033-gif/Ai-ml-dl-nlp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [5]:
a=np.array([1, 2, 3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [7]:
b=np.array([[1,2,3],[1,2,3]])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [9]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
d=np.array([1,2,4,5],dtype=float)
d

array([1., 2., 4., 5.])

In [14]:
#np.arange
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#np.reshape
a=np.arange(1,11).reshape(5,2)
b=np.arange(1,11).reshape(2,5)
print(a)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
#np.ones and np.zeroes
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
#np.random
np.random.random((3,4))

array([[0.84893948, 0.43584072, 0.94315978, 0.99501892],
       [0.62113825, 0.20265145, 0.43875112, 0.46543472],
       [0.60756492, 0.64906071, 0.74419438, 0.91552339]])

In [32]:
#np.linspace lowerrane,upperranfe,no.of.items
np.linspace(-10,10,20,dtype=float)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [35]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#array attributes
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [37]:
#ndim
a1.ndim

1

In [38]:
a2.ndim

2

In [39]:
a3.ndim

3

In [42]:
#shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [45]:
#size
a1.size
a2.size
a3.size

8

In [48]:
a2.itemsize#size of data types int float
a2.dtype

dtype('float64')

changing datatype


In [49]:
a3.dtype


dtype('int64')

In [50]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

**Array Operations**

In [53]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
#scaler operations
a1*2
a1+2


array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [56]:
#relational
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [57]:
#vector operations + - * / **
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

**Functions**

In [58]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[ 0., 40., 55.],
       [72., 40., 64.],
       [43., 44.,  8.]])

In [59]:
np.max(a1)

np.float64(72.0)

In [60]:
np.sum(a1)

np.float64(366.0)

In [ ]:
#max min sum prod

In [61]:
np.max(a1,axis=0)

array([72., 44., 64.])

In [62]:
np.max(a1,axis=1)

array([55., 72., 44.])

In [63]:
#mean median std var
np.mean(a1)

np.float64(40.666666666666664)

In [64]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [67]:
np.log(a3)
#log and exponential function as exp

array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [69]:
#round floor cell
np.round(np.random.random((2,3))*100)


array([[79., 80., 73.],
       [21., 77., 66.]])

In [70]:
np.floor(np.random.random((2,3))*100)

array([[80., 54., 24.],
       [81., 69., 53.]])

In [71]:
np.ceil(np.random.random((2,3))*100)

array([[81., 80., 41.],
       [ 3., 83., 67.]])

# Indexing and **Slicing**

In [72]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [74]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
a1[-1]#last indexing

np.int64(9)

In [77]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
a2[1,2]

np.int64(6)

In [80]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [81]:
a3[1,0,1]

np.int64(5)

In [82]:
a3[0,0,0]

np.int64(0)

In [83]:
a3[1,1,0]

np.int64(6)

In [84]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a1[2:6:2]

array([2, 4])

In [95]:
#1,3,9,11
a2[::2,1::2]


array([[ 1,  3],
       [ 9, 11]])

In [93]:
#finding the corner
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [90]:
#finding first row
a2[0,:]

array([0, 1, 2, 3])

In [91]:
#last column
a2[:,2]

array([ 2,  6, 10])

In [92]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [96]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
a2[1,::3]

array([4, 7])

In [102]:
a2[:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [104]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [105]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [106]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# **Iteraring**

In [107]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [109]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [110]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [111]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping Transpose and Ravel

In [112]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [115]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [117]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking and Hashing

In [118]:
#horizontal stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12).reshape(3,4)
np.hstack((a4,a5))


array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [119]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Splitting


In [121]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [126]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]